/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien;

import javax.swing.ImageIcon;


/**
 *
 * @author ASUS
 */
public class CV_NhanVien extends javax.swing.JFrame {

    private PhieuNhapKho Phieu_Nhap;
    private PhieuXuatKho Phieu_Xuat;
    private ChiTietNhapKho chitietnhap;
    private ChiTietXuatKho chitietxuat;
    private ThongTinTaiKhoan tt_taikhoan;
    private TonKho tonkho;

    /**
     * Creates new form CV_NhanVien
     */
    public CV_NhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        MainBorad = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        TT_TaiKhoan = new javax.swing.JMenuItem();
        Tonkho = new javax.swing.JMenuItem();
        Dangxuat = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        PhieuNhapKho = new javax.swing.JMenuItem();
        PhieuXuatKho = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ChiTietNhapKho = new javax.swing.JMenuItem();
        ChiTietXuatKho = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainBorad.setBackground(new java.awt.Color(255, 255, 204));
        MainBorad.setForeground(new java.awt.Color(255, 255, 204));

        jMenu1.setText("Hệ thống");

        TT_TaiKhoan.setText("Thông tin tài khoản");
        TT_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT_TaiKhoanActionPerformed(evt);
            }
        });
        jMenu1.add(TT_TaiKhoan);

        Tonkho.setText("Tồn kho");
        Tonkho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonkhoActionPerformed(evt);
            }
        });
        jMenu1.add(Tonkho);

        Dangxuat.setText("Đăng xuất");
        Dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(Dangxuat);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Tạo phiếu");

        PhieuNhapKho.setText("Phiếu nhập kho");
        PhieuNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhieuNhapKhoActionPerformed(evt);
            }
        });
        jMenu4.add(PhieuNhapKho);

        PhieuXuatKho.setText("Phiếu xuất kho");
        PhieuXuatKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhieuXuatKhoActionPerformed(evt);
            }
        });
        jMenu4.add(PhieuXuatKho);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sổ chi tiết");

        ChiTietNhapKho.setText("Nhập Kho");
        ChiTietNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiTietNhapKhoActionPerformed(evt);
            }
        });
        jMenu5.add(ChiTietNhapKho);

        ChiTietXuatKho.setText("Xuất Kho");
        ChiTietXuatKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiTietXuatKhoActionPerformed(evt);
            }
        });
        jMenu5.add(ChiTietXuatKho);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainBorad, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainBorad, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhieuNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhieuNhapKhoActionPerformed
        if (Phieu_Nhap == null) {
            Phieu_Nhap = new PhieuNhapKho();
            MainBorad.addTab("Tạo phiếu nhập kho", null, Phieu_Nhap);
        }
        MainBorad.setSelectedComponent(Phieu_Nhap);
    }//GEN-LAST:event_PhieuNhapKhoActionPerformed

    private void PhieuXuatKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhieuXuatKhoActionPerformed
        if (Phieu_Xuat == null) {
            Phieu_Xuat = new PhieuXuatKho();
            MainBorad.addTab("Tạo phiếu xuất kho", null, Phieu_Xuat);
        }
        MainBorad.setSelectedComponent(Phieu_Xuat);
    }//GEN-LAST:event_PhieuXuatKhoActionPerformed

    private void ChiTietNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiTietNhapKhoActionPerformed
        if (chitietnhap == null) {
            chitietnhap = new ChiTietNhapKho();
            MainBorad.addTab("Sổ chi tiết nhập kho", null, chitietnhap);
        }
        MainBorad.setSelectedComponent(chitietnhap);
    }//GEN-LAST:event_ChiTietNhapKhoActionPerformed

    private void ChiTietXuatKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiTietXuatKhoActionPerformed
        if (chitietxuat == null) {
            chitietxuat = new ChiTietXuatKho();
            MainBorad.addTab("Sổ chi tiết xuất kho", null, chitietxuat);
        }
        MainBorad.setSelectedComponent(chitietxuat);
    }//GEN-LAST:event_ChiTietXuatKhoActionPerformed

    private void DangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangxuatActionPerformed
       this.setVisible(false);
       DangNhapNhanVien d = new DangNhapNhanVien();
       d.setVisible(true);
       d.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_DangxuatActionPerformed

    private void TT_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT_TaiKhoanActionPerformed
        if (tt_taikhoan == null) {
           tt_taikhoan = new ThongTinTaiKhoan();
            MainBorad.addTab("Thông tin tài khoản", null, tt_taikhoan);
        }
        MainBorad.setSelectedComponent(tt_taikhoan);
                                                 
    }//GEN-LAST:event_TT_TaiKhoanActionPerformed

    private void TonkhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonkhoActionPerformed
        if (tonkho == null) {
            tonkho = new TonKho();
            MainBorad.addTab("Thông tin tồn kho", null, tonkho);
        }
        MainBorad.setSelectedComponent(tonkho);
    }//GEN-LAST:event_TonkhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CV_NhanVien n = new CV_NhanVien();
                n.setVisible(true);
                n.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChiTietNhapKho;
    private javax.swing.JMenuItem ChiTietXuatKho;
    private javax.swing.JMenuItem Dangxuat;
    private javax.swing.JTabbedPane MainBorad;
    private javax.swing.JMenuItem PhieuNhapKho;
    private javax.swing.JMenuItem PhieuXuatKho;
    private javax.swing.JMenuItem TT_TaiKhoan;
    private javax.swing.JMenuItem Tonkho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
