/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien;


import Entity.Account;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DangNhapNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapNhanVien
     */
    public DangNhapNhanVien() {
        initComponents();
    }

    public boolean checkNull() {
        if (txtTDN.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tài khoản");
            txtTDN.requestFocus();
            return false;
        } else if (pwMK.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mật khẩu");
            pwMK.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTDN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        pwMK = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BT_QuayLai = new javax.swing.JButton();
        QuenMK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhân Viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Tên đăng nhập:");

        txtTDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTDNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Mật khẩu:");

        btnDN.setBackground(new java.awt.Color(204, 0, 51));
        btnDN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDN.setForeground(new java.awt.Color(255, 255, 255));
        btnDN.setText("Đăng Nhập Ngay");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        pwMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwMKActionPerformed(evt);
            }
        });

        jLabel2.setText("hoặc");

        BT_QuayLai.setBackground(new java.awt.Color(0, 0, 0));
        BT_QuayLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BT_QuayLai.setForeground(new java.awt.Color(255, 255, 255));
        BT_QuayLai.setText("Thoát");
        BT_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_QuayLaiActionPerformed(evt);
            }
        });

        QuenMK.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        QuenMK.setForeground(new java.awt.Color(0, 102, 153));
        QuenMK.setText("Quên mật khẩu?");
        QuenMK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                QuenMKAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        QuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuenMKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTDN, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(pwMK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnDN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(BT_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_QuayLai)
                .addGap(18, 18, 18)
                .addComponent(QuenMK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_QuayLaiActionPerformed
        LuaChon l = new LuaChon();
        this.setVisible(false);
        l.setVisible(true);
        l.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_BT_QuayLaiActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        if(checkNull()){
           try{
                String query ="select *\n "
                             +"from DangNhap\n"
                             +"where TenDangNhap = ? and MatKhau = ? and ChucVu = 'nhanvien'";
                Connection conn =  new Database().getConnection();//kết nối sql server
                PreparedStatement ps = conn.prepareStatement(query); // nems câu lệnh query từ netbean sang sql server
                ps.setString(1,txtTDN.getText());
                ps.setString(2, pwMK.getText());
                ResultSet rs = ps.executeQuery();// execute and nhận kết quả trả về
                
                if(rs.next()){
                       Account tt = new Account();
                       CV_NhanVien cv = new CV_NhanVien();
                       cv.setVisible(true);
                       cv.setLocationRelativeTo(null);
                       LuaChon l = new LuaChon();
                       l.setVisible(false);
                       this.setVisible(false);
                       tt.setHoTen(rs.getString("HoTen"));  
                       tt.setMaSo(rs.getString("MaSo"));
                       tt.setChucVu(rs.getString("ChucVu"));
                       tt.setTenDangNhap(rs.getString("TenDangNhap"));
                       tt.setMatKhau(rs.getString("MatKhau"));
                       tt.setGmail(rs.getString("Gmail"));
                       tt.setDiaChi(rs.getString("DiaChi"));
                }
                else {
                    JOptionPane.showMessageDialog(this,"Tên đăng nhập hoặc mật khẩu sai");
                }
                conn.close();
                rs.close();
                ps.close();
                
            }
         
            catch (Exception ex){
            System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnDNActionPerformed

    private void txtTDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTDNActionPerformed

    private void pwMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwMKActionPerformed

    private void QuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuenMKMouseClicked
        this.setVisible(false);
        QuenMK gm = new QuenMK();
        gm.setVisible(true);
        gm.setLocationRelativeTo(null);
    }//GEN-LAST:event_QuenMKMouseClicked

    private void QuenMKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_QuenMKAncestorAdded
        
    }//GEN-LAST:event_QuenMKAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapNhanVien d = new DangNhapNhanVien();
                d.setLocationRelativeTo(null);
                d.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_QuayLai;
    private javax.swing.JLabel QuenMK;
    private javax.swing.JButton btnDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pwMK;
    private javax.swing.JTextField txtTDN;
    // End of variables declaration//GEN-END:variables
}
