/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BT_BatDau = new javax.swing.JButton();
        BT_Thoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HinhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hệ Thống");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 60));

        BT_BatDau.setBackground(new java.awt.Color(204, 0, 51));
        BT_BatDau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BT_BatDau.setForeground(new java.awt.Color(255, 255, 255));
        BT_BatDau.setText("Bắt Đầu Ngay");
        BT_BatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BatDauActionPerformed(evt);
            }
        });
        getContentPane().add(BT_BatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 320, 80));

        BT_Thoat.setBackground(new java.awt.Color(0, 0, 0));
        BT_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BT_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        BT_Thoat.setText("Thoát");
        BT_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ThoatActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 160, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quản Lí Kho Sách Giáo Khoa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        HinhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/phan-mem-quan-ly-kho-online-giai-phap-cho-doanh-nghiep-4.0.jpg"))); // NOI18N
        getContentPane().add(HinhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_BatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BatDauActionPerformed
        LuaChon l = new LuaChon();
        this.setVisible(false);
        l.setVisible(true);
        l.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_BT_BatDauActionPerformed

    private void BT_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ThoatActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát hệ thống không?", "Quản lí kho sách giáo khoa",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienChinh g = new GiaoDienChinh();
                g.setVisible(true);
                g.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_BatDau;
    private javax.swing.JButton BT_Thoat;
    private javax.swing.JLabel HinhNen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
