/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class LuaChon extends javax.swing.JFrame {

    /**
     * Creates new form LuaChon
     */
    public LuaChon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NhanVien = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        BT_QuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lựa Chọn");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Bạn là:");

        NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NhanVien.setForeground(new java.awt.Color(0, 0, 51));
        NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Checking boxes-cuate.png"))); // NOI18N
        NhanVien.setText("Nhân Viên");
        NhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanVienActionPerformed(evt);
            }
        });

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        Admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Admin.setForeground(new java.awt.Color(0, 0, 51));
        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Multitasking-rafiki.png"))); // NOI18N
        Admin.setText("Admin");
        Admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        BT_QuayLai.setBackground(new java.awt.Color(153, 0, 0));
        BT_QuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/previous-sail-icon (1).png"))); // NOI18N
        BT_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_QuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(NhanVien)
                        .addGap(161, 161, 161)
                        .addComponent(Admin))
                    .addComponent(BT_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NhanVien)
                    .addComponent(Admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(BT_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanVienActionPerformed
        this.setVisible(false);
        DangNhapNhanVien n = new DangNhapNhanVien();
        n.setVisible(true);
        n.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_NhanVienActionPerformed

    private void BT_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_QuayLaiActionPerformed

        GiaoDienChinh g = new GiaoDienChinh();
        this.setVisible(false);
        g.setVisible(true);
        g.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_QuayLaiActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        this.setVisible(false);
        DangNhap n = new DangNhap();
        n.setVisible(true);
        n.setLocationRelativeTo(null);
 
        // TODO add your handling code her
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuaChon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuaChon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuaChon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuaChon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                LuaChon l = new LuaChon();
                l.setLocationRelativeTo(null);
                l.setVisible(true); 
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton BT_QuayLai;
    private javax.swing.JButton NhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
