/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Giao_Dien;

import Entity.Account;


/**
 *
 * @author ASUS
 */
public class ThongTinTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinTaiKhoan
     */
    public ThongTinTaiKhoan() {
        initComponents();
        Account tt = new Account();
        lb1HoTen.setText(tt.getHoTen());
        lb2MaSo.setText(tt.getMaSo());
        lb3ChucVu.setText(tt.getChucVu());
        lb4TenDangNhap.setText(tt.getTenDangNhap());
        lb5MatKhau.setText(tt.getMatKhau());
        lb6Gmail.setText(tt.Gmail);
        lb7DiaChi.setText(tt.DiaChi);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMK = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb1HoTen = new javax.swing.JLabel();
        lb2MaSo = new javax.swing.JLabel();
        lb3ChucVu = new javax.swing.JLabel();
        lb4TenDangNhap = new javax.swing.JLabel();
        Change = new javax.swing.JButton();
        lb7DiaChi = new javax.swing.JLabel();
        lb6Gmail = new javax.swing.JLabel();
        lb5MatKhau = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jSeparator1);

        lblMK.setBackground(new java.awt.Color(255, 255, 204));
        lblMK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMK.setForeground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Thông tin tài khoản");

        lb1HoTen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb1HoTen.setForeground(new java.awt.Color(0, 0, 51));
        lb1HoTen.setText("lb1");

        lb2MaSo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb2MaSo.setForeground(new java.awt.Color(0, 0, 51));
        lb2MaSo.setText("lb2");

        lb3ChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb3ChucVu.setForeground(new java.awt.Color(0, 0, 51));
        lb3ChucVu.setText("lb3");

        lb4TenDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb4TenDangNhap.setForeground(new java.awt.Color(0, 0, 51));
        lb4TenDangNhap.setText("lb4");

        Change.setBackground(new java.awt.Color(204, 204, 255));
        Change.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Change.setForeground(new java.awt.Color(102, 0, 51));
        Change.setText("Thay đổi mật khẩu");
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });

        lb7DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb7DiaChi.setForeground(new java.awt.Color(0, 0, 51));
        lb7DiaChi.setText("lb7");

        lb6Gmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb6Gmail.setForeground(new java.awt.Color(0, 0, 51));
        lb6Gmail.setText("lb6");

        lb5MatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb5MatKhau.setForeground(new java.awt.Color(0, 0, 51));
        lb5MatKhau.setText("lb5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Họ Tên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Mã Số:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Chức Vụ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Mật Khẩu:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Tên Đăng Nhập:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Địa Chỉ:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Gmail:");

        javax.swing.GroupLayout lblMKLayout = new javax.swing.GroupLayout(lblMK);
        lblMK.setLayout(lblMKLayout);
        lblMKLayout.setHorizontalGroup(
            lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblMKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb4TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb3ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblMKLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(11, 11, 11)
                            .addComponent(lb2MaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(lblMKLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb1HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb5MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb6Gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb7DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
            .addGroup(lblMKLayout.createSequentialGroup()
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6))
                    .addGroup(lblMKLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        lblMKLayout.setVerticalGroup(
            lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMKLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1HoTen)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2MaSo)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb3ChucVu)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4TenDangNhap)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb5MatKhau)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb6Gmail)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(lblMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb7DiaChi)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addComponent(Change)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jPanel1.add(lblMK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formAncestorAdded

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        this.setVisible(false);
        Change q = new Change();
        q.setVisible(true);
        q.setLocationRelativeTo(null);
    }//GEN-LAST:event_ChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1HoTen;
    private javax.swing.JLabel lb2MaSo;
    private javax.swing.JLabel lb3ChucVu;
    private javax.swing.JLabel lb4TenDangNhap;
    private javax.swing.JLabel lb5MatKhau;
    private javax.swing.JLabel lb6Gmail;
    private javax.swing.JLabel lb7DiaChi;
    private javax.swing.JPanel lblMK;
    // End of variables declaration//GEN-END:variables
}
